import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import localFont from "next/font/local";
import "../styles/globals.css";
import { RegularLayout } from "@/components/layout/regular-layout";

const IBMPlexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-ibm-plex-mono",
});

const drukWide = localFont({
  src: [
    {
      path: "../fonts/DrukWide-Medium-Trial.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/DrukWide-Bold-Trial.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-druk-wide",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${IBMPlexMono.variable} ${drukWide.variable} bg-background`}
      >
        <RegularLayout>{children}</RegularLayout>
      </body>
    </html>
  );
}
